name: vulnerable workflow

on:
  pull_request:
    branches: [main]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Run script
      #      env:
      #  SECRET_KEY: ${{ secrets.SECRET_KEY}}
      run: |
        python script1.py
